# Generated by Django 5.2.4 on 2026-07-20 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='reading_type',
            field=models.CharField(default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='attendance.attendancerecord'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_attendance'),
        ),
    ]
